export { OPEN_EDITMODAL, OPEN_AddMODAL, CLOSE_MODAL, OPEN_DeletMODAL,
        NO_DELETmodal, YES_DELETmodal, DATATABEL, OPEN_CheckOrderModal,
        CLOSE_MODAL_CHECKORDER, DATAORDER, COSTOMERDATA, DATAORDERS, 
        ALLPRODUCT, EDITBTNMODAL, ADDPRODUCT, CURRENTPAGE, PRICEPRODUCTID,
        QUANTITYPRODUCTID, PRICECHANGE, QUANTITYCHANGE, MOBILECATEGORY,
        LAPTOPCATEGORY, TABLETCATEGORY, HEADSETCATEGORY, RADIOFILTERSIDEBAR} from '../slices/ShoppingSlice'